# Generated by Django 4.1.2 on 2022-10-05 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_magicadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclink",
            name="already_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="magiclink",
            name="secret_identifier",
            field=models.CharField(
                default=uuid.UUID("cbe600cc-4859-4111-b77f-470a0586cf0f"),
                editable=False,
                max_length=512,
            ),
        ),
    ]
