# Generated by Django 4.1.2 on 2022-10-05 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_magicadmin", "0002_magiclink_already_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclink",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="magiclink",
            name="secret_identifier",
            field=models.CharField(
                default=uuid.UUID("9e4f84f7-ec68-4eea-8909-9eef820073e9"),
                editable=False,
                max_length=512,
            ),
        ),
    ]
