# Generated by Django 4.1.2 on 2022-10-06 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_magicadmin", "0005_alter_magiclink_secret_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclink",
            name="secret_identifier",
            field=models.CharField(
                default=uuid.UUID("6b73e981-ffc0-4e61-9010-c0fdc2f190d6"),
                max_length=512,
            ),
        ),
    ]
