# Generated by Django 4.1.2 on 2022-10-06 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_magicadmin", "0006_alter_magiclink_secret_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclink",
            name="secret_identifier",
            field=models.CharField(
                default=uuid.UUID("7745bf50-653f-47f3-ac10-b91c6314dd0a"),
                max_length=512,
            ),
        ),
    ]
